apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "alist.fullname" . }}
  labels:
    app: {{ template "alist.name" . }}
    chart: {{ template "alist.chart" . }}
    release: {{ .Release.Name }}
spec:
  accessModes:
  - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
